/**
 * IBM i PASE / Qshell command catalog (IBM 7.4 rzalf + rzahz).
 * In the lab, almost everything is passed to /bin/sh — only IBM i bridges are special.
 */

export type QshellBindingKind = "shell" | "builtin" | "unsupported";

export type QshellCommandBinding = {
  kind: QshellBindingKind;
  note?: string;
};

/**
 * IBM i PASE bridges (rzalf/rzahz) — handled in paseIbmBridges.ts, not passed to POSIX shell.
 * @see https://www.ibm.com/docs/en/i/7.4.0?topic=utilities-pase-i-commands
 */
export const IBM_I_QSH_BUILTINS = new Set([
  "system",
  "getjobid",
  "sysval",
  "setccsid",
  "dspcat",
  "dspmsg",
  "attr",
  "clrtmp",
  "qsh",
  "qsh_out",
  "qsh_inout",
  "admin",
  "setmaps",
  "runcat",
  "rtl_enable",
  "ps",
  "exit",
  "logout",
]);

/**
 * Full PASE for i utility index from IBM documentation.
 * Default lab behavior: pass through to Linux shell unless listed in IBM_I_QSH_BUILTINS or PASE_BLOCKED.
 */
export const PASE_COMMAND_INDEX: readonly string[] = [
  "admin",
  "aixterm",
  "alias",
  "appletviewer",
  "apply",
  "apt",
  "ar",
  "as",
  "attr",
  "awk",
  "banner",
  "basename",
  "bc",
  "bdiff",
  "bfs",
  "bg",
  "bsh",
  "cat",
  "cd",
  "cdc",
  "chgrp",
  "chmod",
  "chown",
  "chroot",
  "cksum",
  "clear",
  "clrtmp",
  "cmp",
  "colrm",
  "comb",
  "comm",
  "command",
  "compress",
  "cp",
  "cpio",
  "csh",
  "csplit",
  "cut",
  "date",
  "dbx",
  "dc",
  "dd",
  "df",
  "diff",
  "diff3",
  "dircmp",
  "dirname",
  "dspcat",
  "dspmsg",
  "du",
  "dump",
  "echo",
  "ed",
  "edit",
  "egrep",
  "env",
  "ex",
  "execerror",
  "expand",
  "expr",
  "extcheck",
  "false",
  "fc",
  "fg",
  "fgrep",
  "file",
  "find",
  "fold",
  "gencat",
  "get",
  "getconf",
  "getjobid",
  "getopt",
  "getopts",
  "grep",
  "hash",
  "head",
  "hostname",
  "iconv",
  "id",
  "idlj",
  "indent",
  "install",
  "ipcrm",
  "ipcs",
  "jar",
  "jarsigner",
  "java",
  "javac",
  "javadoc",
  "javah",
  "javap",
  "jobs",
  "join",
  "keytool",
  "kill",
  "ksh",
  "ksh93",
  "ld",
  "ldedit",
  "lex",
  "line",
  "ln",
  "locale",
  "logger",
  "logname",
  "look",
  "lorder",
  "ls",
  "m4",
  "make",
  "makekey",
  "mkcatdefs",
  "mkdir",
  "mkfifo",
  "mkfontdir",
  "mknod",
  "more",
  "mv",
  "mwm",
  "native2ascii",
  "nawk",
  "newform",
  "nice",
  "nl",
  "nm",
  "nohup",
  "od",
  "orbd",
  "pack",
  "pack200",
  "pagesize",
  "paste",
  "patch",
  "pax",
  "pcat",
  "pg",
  "policytool",
  "pr",
  "print",
  "printenv",
  "printf",
  "prs",
  "ps",
  "psh",
  "pwd",
  "pwdx",
  "qsh",
  "qsh_inout",
  "qsh_out",
  "ranlib",
  "read",
  "red",
  "regcmp",
  "reset",
  "resize",
  "rev",
  "rfile",
  "rgb",
  "rm",
  "rmdel",
  "rmdir",
  "rmic",
  "rmid",
  "rmiregistry",
  "rtl_enable",
  "runcat",
  "sact",
  "serialver",
  "sccs",
  "sccsdiff",
  "sdiff",
  "sed",
  "servertool",
  "set",
  "setccsid",
  "setmaps",
  "sh",
  "size",
  "sleep",
  "slibclean",
  "snapcore",
  "sort",
  "split",
  "strings",
  "strip",
  "stty",
  "sum",
  "syslogd",
  "system",
  "sysval",
  "tab",
  "tabs",
  "tail",
  "tar",
  "tee",
  "test",
  "tic",
  "time",
  "tnameserv",
  "touch",
  "tput",
  "tr",
  "trace",
  "trbsd",
  "trcoff",
  "trcon",
  "trcstop",
  "true",
  "tset",
  "tsort",
  "tty",
  "type",
  "ulimit",
  "umask",
  "unalias",
  "uname",
  "uncompress",
  "unexpand",
  "unget",
  "unifdef",
  "uniq",
  "unpack",
  "unpack200",
  "untab",
  "val",
  "vc",
  "vedit",
  "vi",
  "view",
  "wait",
  "wc",
  "what",
  "which",
  "xargs",
  "xauth",
  "xhost",
  "xlsfonts",
  "xmodmap",
  "xset",
  "xterm",
  "xwd",
  "xwud",
  "yacc",
  "yes",
  "zcat",
];

/** Commands that cannot run in the lab Docker shell (small blocklist). */
export const PASE_BLOCKED: Record<string, string> = {
  aixterm: "X11 not available in lab container.",
  xterm: "X11 not available in lab container.",
  mwm: "AIXwindows not available.",
  X: "X server not available.",
  xauth: "X11 not available.",
  xhost: "X11 not available.",
  xlsfonts: "X11 not available.",
  xmodmap: "X11 not available.",
  xset: "X11 not available.",
  xwd: "X11 not available.",
  xwud: "X11 not available.",
  dbx: "PASE debugger not installed.",
  smit: "SMIT is AIX-only.",
  vi: "Interactive vi not supported on 5250 panel.",
  view: "Interactive vi not supported on 5250 panel.",
  vedit: "Interactive editor not supported on 5250 panel.",
  ed: "Interactive editor not supported on 5250 panel.",
  ex: "Interactive editor not supported on 5250 panel.",
  edit: "Interactive editor not supported on 5250 panel.",
};

const indexSet = new Set(PASE_COMMAND_INDEX.map((name) => name.toLowerCase()));

export function resolveQshellCommand(name: string): QshellCommandBinding {
  const base = name.toLowerCase();

  if (IBM_I_QSH_BUILTINS.has(base)) {
    const note =
      base === "ps"
        ? "IBM i job-mapped ps (use ps -ef for POSIX listing)."
        : "IBM i PASE bridge command.";
    return { kind: "builtin", note };
  }
  if (base in PASE_BLOCKED) {
    return { kind: "unsupported", note: PASE_BLOCKED[base] };
  }
  // Unknown names still go to the shell — Linux may have them (curl, python3, etc.)
  if (!indexSet.has(base)) {
    return { kind: "shell", note: "Passed to container /bin/sh." };
  }
  return { kind: "shell" };
}

export function qshellCommandMapStats(): {
  cataloged: number;
  builtins: number;
  blocked: number;
} {
  return {
    cataloged: PASE_COMMAND_INDEX.length,
    builtins: IBM_I_QSH_BUILTINS.size,
    blocked: Object.keys(PASE_BLOCKED).length,
  };
}
