import path from "node:path";
import {existsSync} from "node:fs";
import {afterEach,beforeEach,describe,expect,it} from "vitest";
import {chromium} from "playwright";
import {closeDatabase,initTestDatabase} from "../../src/db/sqlite.js";
import {createAgentAuthorityRuntime,type AgentAuthorityRuntime} from "../../src/agent-authority/runtime.js";
import {createAuthorityDeskApi} from "../../src/agent-authority/http/authorityDeskApi.js";
import {ScenarioPackService} from "../../src/agent-authority/scenarios/scenarioPackService.js";
import {createLabHttpServer} from "../../src/lab/httpServer.js";
import {createSession,hydrateSessionFromProfile} from "../../src/ibmi-runtime/sessionService.js";
import {registerLiveSession,unregisterLiveSession} from "../../src/lab/liveSessionRegistry.js";
import {removeLabSession,upsertLabSession} from "../../src/lab/sessionRegistry.js";
import {listObjectAuthorities} from "../../src/db/repositories/objectAuthorityRepository.js";
import {listStateChanges} from "../../src/db/repositories/runtimeRepository.js";
import {executeCommand} from "../../src/ibmi-runtime/commandRuntime.js";
import {parseCommand} from "../../src/ibmi-runtime/commandParser.js";
import {grantObjectAuthority} from "../../src/ibmi-runtime/authorityService.js";
import type {Clock,IdGenerator} from "../../src/agent-authority/types.js";

describe("Agent Authority Phase 6.5 guided LCL experience",()=>{
  const cleanup:Array<()=>Promise<void>|void>=[];let runtime:AgentAuthorityRuntime;let n=0;let clock:Clock;let ids:IdGenerator;
  beforeEach(()=>{initTestDatabase();n=0;clock={now:()=>new Date("2026-08-17T01:18:00.000Z")};ids={id:(prefix)=>`${prefix}_p65_${++n}`,nonce:()=>`nonce_p65_${++n}`};});
  afterEach(async()=>{while(cleanup.length)await cleanup.pop()!();closeDatabase();});

  it("keeps Agent Authority undiscoverable when the feature is disabled",async()=>{
    const {url}=await mount();const browser=await launch();const page=await browser.newPage();await introduced(page);await page.goto(`${url}/lab/`);
    await expect.poll(()=>page.locator("#agent-authority-entry").isHidden()).toBe(true);
    expect((await fetch(`${url}/api/agent-authority/walkthrough`)).status).toBe(404);
  },30_000);

  it("guides AA-001 from untrusted message to exact approval, shared state, evidence and proof",async()=>{
    const {url}=await mountEnabled();const browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000}});await introduced(page);
    await page.goto(`${url}/lab/`);await expect.poll(()=>page.getByText("See agent governance").count()).toBe(1);await page.locator("#pick-agent-authority").click();await expect.poll(()=>page.locator("#aa-scenario-cards article").count()).toBe(5);await page.locator('[data-scenario-id="AA-001"]').click();
    await expect.poll(()=>page.getByText("Legacy Control Lab is the synthetic enterprise system.").count()).toBe(1);
    expect(await page.locator("#terminal-frame").count()).toBe(1);expect(await page.getByText("The message is data. It is not permission.").count()).toBeGreaterThan(0);expect(await page.locator("#aa-step-count").textContent()).toBe("Step 1 of 6");expect(await page.locator("#aa-step-instruction").textContent()).toContain("create the agent's governed request");
    const railBox=await page.locator("#coach-rail").boundingBox();const terminalBox=await page.locator(".terminal-panel").boundingBox();expect(railBox!.width).toBeGreaterThanOrEqual(540);expect(terminalBox!.width).toBeGreaterThan(700);
    await page.setViewportSize({width:1100,height:1000});const stackedRail=await page.locator("#coach-rail").boundingBox();const stackedTerminal=await page.locator(".terminal-panel").boundingBox();expect(stackedRail!.y).toBeGreaterThanOrEqual(stackedTerminal!.y+stackedTerminal!.height-1);await page.setViewportSize({width:1600,height:1000});
    await page.getByRole("button",{name:"Create governed request"}).click();await expect.poll(()=>page.locator("#aa-status").textContent()).toContain("Awaiting decision");
    expect(privateAuthority()).toBeUndefined();expect(await page.locator("#aa-current-authority").textContent()).toContain("No private authority");expect(await page.locator("#aa-step-count").textContent()).toBe("Step 2 of 6");expect(await page.locator("#aa-step-command").textContent()).toBe("DSPOBJAUT OBJ(PAYROLL/PAYMST)");expect(await page.locator("#aa-step-expected").textContent()).toContain("should NOT have *USE");
    await page.getByRole("button",{name:"Done — I confirmed it"}).click();await expect.poll(()=>page.locator("#aa-step-count").textContent()).toBe("Step 3 of 6");expect(await page.locator("#aa-step-instruction").textContent()).toContain("User: QSECOFR");expect(await page.locator("#aa-step-instruction").textContent()).toContain("Password: TRAIN");expect(await page.locator("#aa-step-readiness").textContent()).toContain("not ready yet");
    const operator=liveOperator();await expect.poll(()=>page.locator("#aa-step-count").textContent(),{timeout:5_000}).toBe("Step 4 of 6");expect(await page.getByRole("button",{name:"Review request in Authority Desk"}).isVisible()).toBe(true);
    const [desk]=await Promise.all([page.waitForEvent("popup"),page.getByRole("button",{name:"Review request in Authority Desk"}).click()]);await desk.waitForLoadState();await expect.poll(()=>desk.locator("#proposals article").count()).toBe(1);desk.on("dialog",(dialog)=>dialog.accept("guided approval"));await desk.getByRole("button",{name:"Approve"}).click();
    await expect.poll(()=>page.locator("#aa-status").textContent(),{timeout:10_000}).toContain("proof verified");expect(privateAuthority()).toBe("*USE");expect(await page.locator("#aa-current-authority").textContent()).toBe("*USE");expect(await page.locator("#aa-executor").textContent()).toBe("MCPAGENT");expect(await page.locator("#aa-step-count").textContent()).toBe("Step 5 of 6");expect(await page.locator("#aa-step-expected").textContent()).toContain("APCLERK now has *USE");expect(await page.locator("#aa-step-expected").textContent()).toContain("MCPAGENT");
    await page.getByRole("button",{name:"Done — I confirmed the outcome"}).click();await expect.poll(()=>page.locator("#aa-step-count").textContent()).toBe("Step 6 of 6");expect(await page.locator("#aa-step-instruction").textContent()).toContain("inspect what the system recorded");expect(await page.getByRole("button",{name:"Download verified proof"}).count()).toBeGreaterThan(0);
    expect(await page.locator("#aa-evidence-list").textContent()).toContain("CA-style generated audit entry");expect(await page.locator("#aa-evidence-list").textContent()).toContain("MCPAGENT runtime job log");expect(await page.locator("#aa-proof-state").textContent()).toContain("Proof verified");expect(listStateChanges(runtime.adapter.getServiceAttemptId(),"object_authority")).toHaveLength(1);
    expect(await desk.getByRole("link",{name:/Back to Agent Authority walkthrough/}).getAttribute("href")).toBe("/lab/?path=agentauthority");expect(operator.token).toBeTruthy();
  },60_000);

  it("renders hostile walkthrough content as inert text and shows denial without mutation",async()=>{
    const {url}=await mountEnabled();const operator=liveOperator();const browser=await launch();const page=await browser.newPage();await introduced(page);const hostile='<img id="aa-guide-xss" src=x onerror="window.__AA_GUIDE_XSS__=true">';
    await page.route("**/api/agent-authority/walkthrough",async(route)=>{const response=await route.fetch();const body=await response.json();body.message.text=hostile;await route.fulfill({response,json:body});});
    await page.goto(`${url}/lab/?path=agentauthority`);await expect.poll(()=>page.locator("#aa-scenario-cards article").count()).toBe(5);await page.locator('[data-scenario-id="AA-001"]').click();await expect.poll(()=>page.locator("#aa-message-text").textContent()).toBe(hostile);expect(await page.locator("#aa-guide-xss,#agent-authority-panel img,#agent-authority-panel script").count()).toBe(0);expect(await page.evaluate(()=>Reflect.get(window,"__AA_GUIDE_XSS__"))).toBeUndefined();
    await page.getByRole("button",{name:"Create governed request"}).click();const status=await (await fetch(`${url}/api/agent-authority/walkthrough`)).json() as any;const denied=await fetch(`${url}/api/agent-authority/proposals/${status.proposal.id}/deny`,{method:"POST",headers:{"X-Lab-Session-Token":operator.token,"Content-Type":"application/json"},body:JSON.stringify({reason:"Message is not authorization"})});expect(denied.status).toBe(200);
    await expect.poll(()=>page.locator("#aa-status").textContent(),{timeout:10_000}).toContain("Denied");expect(privateAuthority()).toBeUndefined();expect(await page.locator("#aa-current-authority").textContent()).toContain("No private authority");expect(await page.locator("#aa-step-count").textContent()).toBe("Step 5 of 6");expect(await page.locator("#aa-step-expected").textContent()).toContain("still have no *USE");await page.getByRole("button",{name:"Done — I confirmed the outcome"}).click();await expect.poll(()=>page.locator("#aa-step-count").textContent()).toBe("Step 6 of 6");expect(await page.locator("#aa-proof-state").textContent()).toContain("Proof verified");
  },30_000);

  it("renders the five-scenario chooser, safe-read curriculum, boundary denial, and green terminal commands",async()=>{
    const {url}=await mountEnabled();const browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000}});await introduced(page);await page.goto(`${url}/lab/?path=agentauthority`);
    await expect.poll(()=>page.locator("#aa-scenario-cards article").count()).toBe(5);expect(await page.locator("#agent-authority-entry").count()).toBe(1);expect(await page.getByText("More Access Than Necessary").count()).toBe(1);expect(await page.getByText("Outside the Boundary").count()).toBe(1);
    await page.locator('[data-scenario-id="AA-005"]').click();await page.getByRole("button",{name:"Attempt request"}).click();await expect.poll(()=>page.locator("#aa-step-command").textContent()).toBe("DSPOBJAUT OBJ(CLAIMS400/CLAIMMST)");expect(await page.locator("#aa-step-command").evaluate((node)=>getComputedStyle(node).fontFamily)).toMatch(/mono|Cascadia|Consolas/i);expect(await page.locator("#aa-step-command").evaluate((node)=>getComputedStyle(node).color)).toBe("rgb(87, 242, 161)");expect(await page.locator("#aa-evidence-list").textContent()).toContain("Boundary denial receipt");
    await page.locator("#aa-back-to-scenarios").click();await page.locator('[data-scenario-id="AA-004"]').click();await page.getByRole("button",{name:"Run safe investigation"}).click();await expect.poll(()=>page.locator("#aa-evidence-list li").count()).toBe(3);expect(await page.locator("#aa-evidence-list").textContent()).toContain("No human approval required");expect(await page.getByRole("button",{name:"Propose *ALL → *USE"}).isVisible()).toBe(true);
  },30_000);

  it("drives AA-002 through authenticated denial, new exact request, and approval",async()=>{
    const {url}=await mountEnabled();const operator=liveOperator();const browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000}});await introduced(page);await page.goto(`${url}/lab/?path=agentauthority`);
    await expect.poll(()=>page.locator("#aa-scenario-cards article").count()).toBe(5);await page.locator('[data-scenario-id="AA-002"]').click();await page.getByRole("button",{name:"Create *ALL request"}).click();
    const broad=await scenario(url,"AA-002");const all=broad.proposals.find((proposal:any)=>proposal.action.arguments.authority==="*ALL");expect(all).toBeTruthy();
    await expect.poll(()=>page.getByRole("button",{name:"Review request in Authority Desk"}).count()).toBe(1);const [desk]=await Promise.all([page.waitForEvent("popup"),page.getByRole("button",{name:"Review request in Authority Desk"}).click()]);await desk.waitForLoadState();const allCard=desk.locator(`[data-proposal-id="${all.id}"]`);await expect.poll(()=>allCard.count()).toBe(1);expect(await allCard.textContent()).toContain("Authority*ALL");expect(await allCard.textContent()).toContain(all.actionHash);
    desk.once("dialog",(dialog)=>dialog.accept("Broader than the stated need"));await allCard.getByRole("button",{name:"Deny"}).click();await expect.poll(()=>desk.locator("#history").textContent()).toContain(all.id);
    await expect.poll(async()=>((await scenario(url,"AA-002")).status)).toBe("in_progress");await page.locator("#aa-back-to-scenarios").click();const chooserCard=page.locator('[data-scenario-id="AA-002"]').locator("xpath=..");await expect.poll(()=>chooserCard.textContent()).toContain("in progress");await page.locator('[data-scenario-id="AA-002"]').click();await expect.poll(()=>page.getByRole("button",{name:"Submit new *USE request"}).count()).toBe(1);
    await page.getByRole("button",{name:"Submit new *USE request"}).click();const narrowed=await scenario(url,"AA-002");const use=narrowed.proposals.find((proposal:any)=>proposal.action.arguments.authority==="*USE");expect(use.id).not.toBe(all.id);expect(use.actionHash).not.toBe(all.actionHash);
    await desk.getByRole("button",{name:"Refresh"}).click();const useCard=desk.locator(`[data-proposal-id="${use.id}"]`);await expect.poll(()=>useCard.count()).toBe(1);expect(await useCard.textContent()).toContain("Authority*USE");desk.once("dialog",(dialog)=>dialog.accept("Least privilege"));await useCard.getByRole("button",{name:"Approve"}).click();
    await expect.poll(async()=>((await scenario(url,"AA-002")).status),{timeout:10_000}).toBe("complete");await expect.poll(()=>page.locator("#aa-step-command").textContent()).toBe("DSPOBJAUT OBJ(PAYROLL/PAYMST)");await expectGreenCommand(page);expect(authority("AUDIT")).toBe("*USE");expect((await scenario(url,"AA-002")).proposals.find((proposal:any)=>proposal.id===all.id).status).toBe("denied");expect(operator.token).toBeTruthy();
  },60_000);

  it("drives AA-003 through an ordinary terminal mutation and stale approval invalidation",async()=>{
    const {url}=await mountEnabled();const operator=liveOperator();const browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000}});await introduced(page);await page.goto(`${url}/lab/?path=agentauthority`);await expect.poll(()=>page.locator("#aa-scenario-cards article").count()).toBe(5);await page.locator('[data-scenario-id="AA-003"]').click();await page.getByRole("button",{name:"Create governed request"}).click();
    const created=await scenario(url,"AA-003");const proposal=created.proposals[0];const change="GRTOBJAUT OBJ(PAYROLL/PAYMST) USER(OLDVENDOR) AUT(*EXCLUDE)";await expect.poll(()=>page.locator("#aa-step-command").textContent()).toBe(change);await expectGreenCommand(page);
    const parsed=parseCommand(change);expect(parsed).not.toBeNull();const mutation=executeCommand(operator.session,parsed!);expect(mutation).toMatchObject({kind:"message",command:"GRTOBJAUT"});expect(authority("OLDVENDOR")).toBe("*EXCLUDE");
    await expect.poll(()=>page.getByRole("button",{name:"Review request in Authority Desk"}).count()).toBe(1);const [desk]=await Promise.all([page.waitForEvent("popup"),page.getByRole("button",{name:"Review request in Authority Desk"}).click()]);await desk.waitForLoadState();const card=desk.locator(`[data-proposal-id="${proposal.id}"]`);await expect.poll(()=>card.count()).toBe(1);desk.on("dialog",(dialog)=>dialog.accept("Approve captured request"));await card.getByRole("button",{name:"Approve"}).click();
    await expect.poll(async()=>((await scenario(url,"AA-003")).status),{timeout:10_000}).toBe("complete");const final=await scenario(url,"AA-003");expect(final.proposals[0]).toMatchObject({status:"invalidated",executionStatus:null,proof:{verified:true}});expect(authority("OLDVENDOR")).toBe("*EXCLUDE");expect(listStateChanges(runtime.adapter.getServiceAttemptId(),"object_authority")).toHaveLength(0);await expect.poll(()=>page.locator("#aa-step-command").textContent()).toBe("DSPOBJAUT OBJ(PAYROLL/PAYMST)");expect(await page.locator("#aa-step-expected").textContent()).toContain("OLDVENDOR remains *EXCLUDE");expect(await page.locator("#aa-proof-state").textContent()).toContain("Proof verified");expect(operator.token).toBeTruthy();
  },60_000);

  it("shows a cancellable scenario completion and preserves truthful chooser progress",async()=>{
    const {url}=await mountEnabled();const operator=liveOperator();const browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000}});await introduced(page);await page.goto(`${url}/lab/?path=agentauthority`);await expect.poll(()=>page.locator("#aa-lab-progress").textContent()).toBe("Progress 0 / 5");
    const before=listObjectAuthorities("CLAIMS400","CLAIMS400","CLAIMMST").find((row)=>row.userName==="AUDIT")?.authority;await page.locator('[data-scenario-id="AA-005"]').click();await page.getByRole("button",{name:"Attempt request"}).click();await page.getByRole("button",{name:"Finish scenario"}).click();await expect.poll(()=>page.locator("#aa-completion-kicker").textContent()).toBe("Scenario complete");expect(await page.locator("#aa-completion-lesson").textContent()).toContain("outside the agent's delegated authority");expect(await page.locator("#aa-return-message").textContent()).toContain("10 seconds");
    await page.getByRole("button",{name:"Stay here"}).click();expect(await page.locator("#aa-return-message").textContent()).toContain("cancelled");await page.waitForTimeout(1100);expect(await page.locator("#aa-scenario-complete").isVisible()).toBe(true);await page.getByRole("button",{name:"Return now"}).click();await expect.poll(()=>page.locator("#aa-lab-progress").textContent()).toBe("Progress 1 / 5");expect(await page.locator('[data-scenario-id="AA-005"]').locator("xpath=..").textContent()).toContain("complete");expect(listObjectAuthorities("CLAIMS400","CLAIMS400","CLAIMMST").find((row)=>row.userName==="AUDIT")?.authority).toBe(before);
    await page.locator('[data-scenario-id="AA-003"]').click();await page.getByRole("button",{name:"Create governed request"}).click();await page.locator("#aa-back-to-scenarios").click();await expect.poll(()=>page.locator('[data-scenario-id="AA-003"]').locator("xpath=..").textContent()).toContain("in progress");expect(await page.locator("#aa-lab-progress").textContent()).toBe("Progress 1 / 5");
    await page.locator('[data-scenario-id="AA-002"]').click();await page.getByRole("button",{name:"Create *ALL request"}).click();const broad=await scenario(url,"AA-002");expect(runtime.approvals.approve(broad.proposals[0].id,operator.session,"Human accepted broad access").status).toBe("succeeded");await expect.poll(()=>page.getByRole("button",{name:"Finish scenario"}).count()).toBe(1);await page.getByRole("button",{name:"Finish scenario"}).click();await expect.poll(()=>page.locator("#aa-completion-kicker").textContent()).toBe("Scenario complete with warning");expect(await page.locator("#aa-completion-lesson").textContent()).toContain("human approval alone did not guarantee least privilege");await page.getByRole("button",{name:"Return now"}).click();await expect.poll(()=>page.locator("#aa-lab-progress").textContent()).toBe("Progress 2 / 5");expect(await page.locator('[data-scenario-id="AA-002"]').locator("xpath=..").textContent()).toContain("complete with warning");
  },60_000);

  it("renders the intentional 5 of 5 lab completion and final navigation choices",async()=>{
    const {url}=await mountEnabled();const operator=liveOperator();const scenarios=new ScenarioPackService(runtime);
    const aa1=scenarios.act("AA-001","create_initial_request");expect(runtime.approvals.approve(aa1.proposals[0].id,operator.session,"AA-001").status).toBe("succeeded");
    const aa2=scenarios.act("AA-002","create_initial_request");expect(runtime.approvals.approve(aa2.proposals[0].id,operator.session,"AA-002 warning").status).toBe("succeeded");
    const aa3=scenarios.act("AA-003","create_initial_request");grantObjectAuthority("CLAIMS400","PAYROLL","PAYMST","OLDVENDOR","*EXCLUDE");expect(runtime.approvals.approve(aa3.proposals[0].id,operator.session,"AA-003 stale").status).toBe("invalidated");
    scenarios.act("AA-004","run_investigation");const aa4=scenarios.act("AA-004","create_mutation_request");expect(runtime.approvals.approve(aa4.proposals[0].id,operator.session,"AA-004").status).toBe("succeeded");scenarios.act("AA-005","attempt_out_of_scope_request");
    const browser=await launch();const page=await browser.newPage({viewport:{width:1600,height:1000}});await introduced(page);await page.goto(`${url}/lab/?path=agentauthority`);await expect.poll(()=>page.locator("#aa-lab-complete").isVisible()).toBe(true);expect(await page.locator("#aa-scenario-cards").isHidden()).toBe(true);expect(await page.locator("#aa-lab-progress").textContent()).toBe("Progress 5 / 5");expect(await page.locator("#aa-lab-complete").textContent()).toContain("Agent Authority Lab complete");for(const lesson of ["Data ≠ authority","Exact approval ≠ good judgment","Approval is state-bound","Autonomy can be proportional","Delegation has a hard edge"])expect(await page.locator("#aa-lab-complete").textContent()).toContain(lesson);expect(await page.locator("#aa-return-countdown").isHidden()).toBe(true);
    await page.getByRole("button",{name:"Review scenarios"}).click();await expect.poll(()=>page.locator("#aa-scenario-cards").isVisible()).toBe(true);expect(await page.locator("#aa-lab-complete").isHidden()).toBe(true);expect(await page.locator("#aa-panel-title").textContent()).toBe("Review scenarios");expect(await page.locator("#aa-lab-progress").textContent()).toBe("Progress 5 / 5");expect(await page.locator(".agent-scenario-card").count()).toBe(5);
    await page.locator('[data-scenario-id="AA-005"]').click();await expect.poll(()=>page.locator("#aa-scenario-complete").isVisible()).toBe(true);expect(await page.locator("#aa-completion-lesson").textContent()).toContain("outside the agent's delegated authority");expect(await page.locator("#aa-return-countdown").isHidden()).toBe(true);await page.waitForTimeout(1100);expect(await page.locator("#aa-scenario-complete").isVisible()).toBe(true);expect(await page.locator("#aa-back-to-scenarios").isVisible()).toBe(true);await page.locator("#aa-back-to-scenarios").click();await expect.poll(()=>page.locator("#aa-lab-complete").isVisible()).toBe(true);
    await page.getByRole("button",{name:"Review scenarios"}).click();await page.getByRole("button",{name:"Lab completion summary"}).click();await expect.poll(()=>page.locator("#aa-lab-complete").isVisible()).toBe(true);await page.getByRole("button",{name:"Return to LCL launcher"}).click();await expect.poll(()=>page.locator("#lane-chooser").isVisible()).toBe(true);
  },60_000);

  async function mountEnabled(){runtime=createAgentAuthorityRuntime({target:"lcl",clock,ids,principalId:"guided-agent",guidedAa001:true});return mount({authorityDeskHandler:createAuthorityDeskApi(runtime,"CLAIMS400"),authorityDeskPublicDir:path.resolve("public/authority-desk")});}
  async function mount(extra:Partial<Parameters<typeof createLabHttpServer>[0]>={}){const server=createLabHttpServer({port:0,host:"127.0.0.1",ironTermPublicDir:path.resolve("public"),systemName:"CLAIMS400",websockifyPort:6080,...extra});await new Promise<void>((resolve)=>server.listen(0,"127.0.0.1",resolve));cleanup.push(()=>new Promise<void>((resolve)=>server.close(()=>resolve())));return {url:`http://127.0.0.1:${(server.address() as {port:number}).port}`};}
  async function launch(){const executable=browserPath();const browser=await chromium.launch({headless:true,...(executable?{executablePath:executable}:{}),args:["--no-sandbox"]});cleanup.push(()=>browser.close());return browser;}
  async function introduced(page:import("playwright").Page){await page.addInitScript(()=>localStorage.setItem("lab.launcher.introduced","1"));}
  async function scenario(url:string,id:string){return await (await fetch(`${url}/api/agent-authority/scenarios/${id}`)).json() as any;}
  async function expectGreenCommand(page:import("playwright").Page){expect(await page.locator("#aa-step-command").evaluate((node)=>getComputedStyle(node).fontFamily)).toMatch(/mono|Cascadia|Consolas/i);expect(await page.locator("#aa-step-command").evaluate((node)=>getComputedStyle(node).color)).toBe("rgb(87, 242, 161)");}
  function liveOperator(){const session=createSession("CLAIMS400");session.signedOn=true;session.userName="QSECOFR";session.job.user="QSECOFR";hydrateSessionFromProfile(session,"QSECOFR","CLAIMS400");registerLiveSession(session);const snapshot=upsertLabSession({sessionId:session.id,systemName:"CLAIMS400",userName:"QSECOFR",screenId:"MAIN",lane:"operator",updatedAt:new Date().toISOString()});cleanup.push(()=>{unregisterLiveSession(session.id);removeLabSession(session.id);});return {session,token:snapshot.sessionToken!};}
  function privateAuthority(){return listObjectAuthorities("CLAIMS400","PAYROLL","PAYMST").find((row)=>row.userName==="APCLERK")?.authority;}
  function authority(user:string){return listObjectAuthorities("CLAIMS400","PAYROLL","PAYMST").find((row)=>row.userName===user)?.authority;}
});

function browserPath():string|undefined {const configured=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;if(configured)return configured;const managed=chromium.executablePath();if(existsSync(managed))return undefined;if(existsSync("/tmp/chromium"))return "/tmp/chromium";throw new Error("A Playwright-compatible Chromium binary is required");}
