import {getUserProfile} from "../db/repositories/userProfileRepository.js";
import type {AgentAuthorityRuntime} from "../agent-authority/runtime.js";
import {ScenarioPackService} from "../agent-authority/scenarios/scenarioPackService.js";
import type {ScfAssessment,ScfAssessmentRow,ScfAssessmentStatus,ScfEvidenceReference} from "./types.js";

type ScenarioProjection=ReturnType<ScenarioPackService["project"]>;
type ScenarioStatus=ScenarioProjection["status"];

export class ScfAssessorService {
  private readonly scenarios:ScenarioPackService;
  constructor(private readonly runtime:AgentAuthorityRuntime,private readonly systemName:string){this.scenarios=new ScenarioPackService(runtime);}

  assess():ScfAssessment {
    const states=Object.fromEntries(["AA-001","AA-002","AA-003","AA-004","AA-005"].map((id)=>[id,this.scenarios.project(id as Parameters<ScenarioPackService["project"]>[0])])) as Record<string,ScenarioProjection>;
    const profile=getUserProfile(this.systemName,"MCPAGENT");
    const rows=this.rows(states,profile);
    const summary={pass:0,fail:0,partial:0,not_tested:0,no_evidence:0} satisfies Record<ScfAssessmentStatus,number>;
    for(const row of rows)summary[row.status]+=1;
    return {
      profile:{id:"SCF-2026.3-LCL-AA",title:"SCF 2026.3 · Agent Authority",scfRelease:"2026.3",kind:"assessor_guidepost",claim:"Implementation evidence, not an SCF certification or attestation."},
      boundary:{system:this.systemName,environment:"Legacy Control Lab Community Edition",target:"Synthetic PAYROLL/PAYMST Agent Authority workflow",interval:"Current persistent lab volume at assessment time",limitations:["Synthetic IBM i learning environment, not a production partition","Selected SCF 2026.3 CAA and CAC controls only","A blank row is not converted into a pass","Control operation and assessment occur inside one lab deployment"]},
      generatedAt:this.runtime.clock.now().toISOString(),summary,
      evidenceContract:{population:"Every Agent Authority scenario, proposal and bounded receipt currently present in this lab volume",sources:["Agent Authority scenario projections","Canonical proposal and approval records","Hash-chained decision and execution receipts","Portable proof-bundle verification","CLAIMS400 user-profile state"],integrity:"Rows use live runtime state; terminal outcomes require independently verifiable proof before they can pass.",knownExclusions:["Enterprise credential vault and rotation records","Quarterly production access-review records","External immutable evidence repository","Production data-feed inventory and retention configuration"]},
      rows,
    };
  }

  private rows(s:Record<string,ScenarioProjection>,profile:ReturnType<typeof getUserProfile>):ScfAssessmentRow[]{
    const aa1=s["AA-001"]!;const aa2=s["AA-002"]!;const aa3=s["AA-003"]!;const aa4=s["AA-004"]!;const aa5=s["AA-005"]!;
    const aa1Proof=this.hasVerifiedTerminalProof(aa1);const aa3Proof=this.hasVerifiedTerminalProof(aa3);
    const anyVerified=[aa1,aa2,aa3,aa4].some((state)=>this.hasVerifiedTerminalProof(state));
    const aa2BroadApproved=aa2.status==="complete_with_warning";
    const aa2Narrow=aa2.status==="complete"&&aa2.proposals.some((p)=>p.action.arguments.authority==="*USE"&&p.status==="consumed"&&p.proof.verified);
    const aa4Observed=aa4.observations.length>=3;
    const profileObserved=Boolean(profile);
    const serviceIsPowerful=profile?.specialAuthorities?.split(/\s+/).includes("*SECADM")??false;
    const refs=(...states:ScenarioProjection[])=>states.flatMap((state)=>this.references(state));
    const scenario=(id:string,label:string):ScfEvidenceReference=>({type:"scenario",id,label,href:`/lab/?path=agentauthority&scenario=${id}`});
    return [
      this.row("CPL-29","Control Assurance Automation (CAA) Oversight","Govern automated assurance as a controlled capability with accountable ownership, review and exception handling.","Can the assessor identify the governed automation boundary, accountable decisions and unresolved exceptions?","Agent Authority exposes deterministic policy decisions, human holds, denials, invalidations and proof outcomes across five bounded scenarios.","partial",this.started([aa1,aa2,aa3,aa4,aa5])?"partial":"not_tested","The lab demonstrates decision governance, but it doesn’t evidence an enterprise CAA owner, periodic oversight cadence or production exception process.","Enterprise ownership and recurring oversight remain outside the lab boundary.",["AA-001","AA-002","AA-003","AA-004","AA-005"],[scenario("AA-001","Agent Authority scenario pack"),...refs(aa1,aa2,aa3,aa4,aa5)]),
      this.row("CPL-30","CAA Evidence Integrity & Provenance","Preserve evidence provenance, integrity and the chain from source observation through conclusion.","Can another assessor bind the conclusion to source, method, actor, time and an integrity-verifiable record?","Canonical action hashes, state-bound approvals, hash-chained receipts and portable proof bundles bind decisions to execution and IBM i evidence.","like_for_like",aa1Proof?"pass":this.statusUntilTerminal(aa1.status),aa1Proof?"A verified proof bundle preserves the decision path and runtime evidence for AA-001.":"No terminal, independently verified AA-001 proof bundle exists yet.",aa1Proof?null:"Complete AA-001 to produce and independently verify the portable proof bundle.",["AA-001"],refs(aa1)),
      this.row("CFG-23","CAA Change Control","Govern changes to assurance logic and execution behavior through controlled, attributable versions.","Are the policy, canonical action and execution decision versioned and bound to what actually ran?","Agent Authority binds policy ID/version, tool version, canonical action hash and approval to each proposal and receipt chain.","partial",anyVerified?"partial":this.anyStarted([aa1,aa2,aa3,aa4]),anyVerified?"Runtime decisions are version-bound, but repository change approvals and deployment provenance aren’t included in the proof bundle.":"No completed governed execution is available for inspection.","Git history exists outside the evidence package; a production-grade assessment would require reviewed release provenance.",["AA-001","AA-002","AA-003","AA-004"],refs(aa1,aa2,aa3,aa4)),
      this.row("CFG-24","CAA Unauthorized Change Detection","Detect when protected state or assurance-relevant logic changes outside the approved state.","Does approval fail closed when the state it authorized no longer exists?","AA-003 snapshots authority state, mutates it through the ordinary CLAIMS400 path, then proves the stale proposal is invalidated without broker mutation.","like_for_like",aa3Proof&&aa3.proposals.some((p)=>p.status==="invalidated")?"pass":this.statusUntilTerminal(aa3.status),aa3Proof?"The approved action was rejected because the protected precondition changed.":"AA-003 hasn’t yet produced verified invalidation evidence.",aa3Proof?null:"Run AA-003 through the ordinary mutation and approval attempt.",["AA-003"],refs(aa3)),
      this.row("CFG-25","CAA Separation of Duties","Separate control operation, assurance modification, approval and execution so one actor can’t silently grade its own work.","Can the evidence distinguish requester, approver and executor, and show that approval can’t rewrite the requested action?","The agent proposes, QSECOFR reviews through Authority Desk, and MCPAGENT executes only the exact action hash; a new action requires a new proposal.","like_for_like",aa1Proof?"pass":this.statusUntilTerminal(aa1.status),aa1Proof?"AA-001 proves distinct request, human decision and service execution identities.":"The separation exists in design but hasn’t produced terminal evidence in this volume.",aa1Proof?null:"Complete AA-001 with a human decision and inspect its proof bundle.",["AA-001","AA-002"],refs(aa1,aa2)),
      this.row("MON-37","CAA Data Feed Identification","Identify and bound the data feeds used by control-assurance automation.","Can the assessor enumerate exactly which IBM i observations informed the decision?","AA-004 records three bounded observations: user profile, object authority and recent audit events, each with its own receipt.","partial",aa4Observed?"partial":this.statusUntilObserved(aa4),aa4Observed?"The three decision inputs are explicit and receipt-bound.":"The investigation feeds haven’t been collected.","The lab demonstrates feed identification, not enterprise source ownership, availability monitoring or retention.",["AA-004"],refs(aa4)),
      this.row("DCH-41","CAA Aggregated Telemetry","Combine relevant telemetry without erasing source identity, limitations or provenance.","Does aggregation preserve the individual source records and their role in the conclusion?","AA-004 joins profile, authority and audit observations in one decision path while retaining each source receipt separately.","partial",aa4Observed?"partial":this.statusUntilObserved(aa4),aa4Observed?"The decision view aggregates three sources without flattening their receipt identity.":"No multi-source investigation has been run.","This is a bounded demonstration, not a production telemetry pipeline with completeness and timeliness controls.",["AA-004"],refs(aa4)),
      this.row("IAC-50","Compliance as Code (CAC) Identity Governance","Assign and govern identities used by compliance automation.","Is the automation identity explicit, attributable and constrained to a defined service purpose?","Successful mutations execute as the dedicated MCPAGENT profile and record that actor in job log, audit and proof evidence.","partial",profileObserved?"partial":anyVerified?"not_tested":"no_evidence",profileObserved?`MCPAGENT is present as ${profile!.status} ${profile!.userClass} with ${profile!.specialAuthorities}.`:"MCPAGENT hasn’t been materialized because no governed execution has required it.","The lab has no owner attestation, periodic recertification or deprovisioning record for the service identity.",["AA-001","AA-002","AA-004"],[{type:"service_identity",id:"MCPAGENT",label:"CLAIMS400 service profile"},...refs(aa1,aa2,aa4)]),
      this.row("IAC-51","CAC Least Privileges","Limit compliance-automation identities to the minimum authority required for their assigned functions.","Could the collection or execution identity alter more protected state than the assessed function requires?","MCPAGENT has no *ALLOBJ and executes a narrow broker allow-list, but its synthetic IBM i profile carries *SECADM.","not_demonstrated",aa2BroadApproved||serviceIsPowerful?"fail":aa2Narrow?"partial":this.statusUntilTerminal(aa2.status),aa2BroadApproved?"AA-002 proves that an approved *ALL request can still violate least privilege.":serviceIsPowerful?"The broker is narrow, but the service profile’s *SECADM authority prevents a like-for-like least-privilege conclusion.":aa2Narrow?"The *ALL request was denied and *USE executed, but service-profile privilege still needs independent treatment.":"Least privilege hasn’t been exercised in this volume.","Remove or technically justify *SECADM, then prove the reduced profile still supports the exact broker operations.",["AA-002"],[{type:"service_identity",id:"MCPAGENT",label:"MCPAGENT profile authority"},...refs(aa2)]),
      this.row("IAC-52","CAC Credential Lifecycle Management","Govern issuance, rotation, expiration, revocation and ownership of automation credentials.","Where is the lifecycle record for every credential available to the automation?","LCL deliberately gives MCPAGENT no password and no external API credential.","not_demonstrated","no_evidence","Absence of a password reduces one credential path, but it isn’t evidence of a governed enterprise credential lifecycle.","No issuance, rotation, revocation, ownership or periodic-review record exists in the lab evidence boundary.",[],profileObserved?[{type:"service_identity",id:"MCPAGENT",label:"Passwordless disabled service profile"}]:[]),
      this.row("IAC-53","CAC Credentials Management","Protect, store and use automation credentials through controlled mechanisms.","Can the assessor show where credentials reside, who can retrieve them and how their use is logged?","The deterministic local workflow needs no cloud key, OAuth token or live IBM i password; operator approval uses an authenticated lab session.","partial",profileObserved||anyVerified?"partial":"not_tested","The lab removes several secret classes, but it doesn’t demonstrate vaulting, retrieval controls or rotation for a production deployment.","Production credential-storage and access evidence are intentionally outside Community Edition.",["AA-001"],[{type:"scope",id:"local-only",label:"Local deterministic deployment boundary"},...refs(aa1)]),
      this.row("IAO-15","CAA Automation","Automate control-assurance activities while preserving bounded scope, accountable decisions and reviewable outcomes.","Does the automation produce a reproducible result without silently converting uncertainty or denial into success?","The broker permits bounded reads, holds sensitive writes, rejects out-of-bound requests and emits verifiable terminal proof.","like_for_like",anyVerified&&aa5.status==="complete"?"pass":this.started([aa1,aa2,aa3,aa4,aa5])?"partial":"not_tested",anyVerified&&aa5.status==="complete"?"The volume contains both a verified governed outcome and a proved boundary denial.":"The design is present, but the current volume doesn’t yet contain both terminal proof and an exercised hard boundary.",anyVerified&&aa5.status==="complete"?null:"Complete one governed terminal scenario and AA-005.",["AA-001","AA-004","AA-005"],[...refs(aa1,aa4,aa5),scenario("AA-005","Delegation boundary scenario")]),
    ];
  }

  private row(controlId:string,controlTitle:string,scfIntent:string,assessorQuestion:string,lclImplementation:string,fit:ScfAssessmentRow["fit"],status:ScfAssessmentStatus,conclusion:string,gap:string|null,scenarios:string[],evidence:ScfEvidenceReference[]):ScfAssessmentRow{return {controlId,controlTitle,scfIntent,assessorQuestion,lclImplementation,fit,status,conclusion,gap,scenarios,evidence:this.unique(evidence)};}
  private references(state:ScenarioProjection):ScfEvidenceReference[]{const refs:ScfEvidenceReference[]=[{type:"scenario",id:state.scenario.id,label:`${state.scenario.id} · ${state.scenario.title}`,href:`/lab/?path=agentauthority&scenario=${state.scenario.id}`}];for(const proposal of state.proposals){refs.push({type:"proposal",id:proposal.id,label:`${proposal.status} · ${proposal.actionHash.slice(0,12)}…`,href:"/lab/authority/"});if(proposal.proof.available)refs.push({type:"proof_bundle",id:proposal.id,label:proposal.proof.verified?"Verified portable proof":"Portable proof failed verification",href:`/api/agent-authority/proposals/${encodeURIComponent(proposal.id)}/proof`});}for(const observation of state.observations)refs.push({type:"receipt_chain",id:observation.receiptId,label:observation.tool});if(state.denial)refs.push({type:"receipt_chain",id:state.denial.id,label:"Boundary denial receipt"});return refs;}
  private unique(refs:ScfEvidenceReference[]){const seen=new Set<string>();return refs.filter((ref)=>{const key=`${ref.type}:${ref.id}`;if(seen.has(key))return false;seen.add(key);return true;});}
  private hasVerifiedTerminalProof(state:ScenarioProjection){return state.proposals.some((proposal)=>proposal.proof.verified&&["denied","expired","invalidated","consumed"].includes(proposal.status));}
  private started(states:ScenarioProjection[]){return states.some((state)=>state.status!=="not_started");}
  private anyStarted(states:ScenarioProjection[]):ScfAssessmentStatus{return this.started(states)?"partial":"not_tested";}
  private statusUntilTerminal(status:ScenarioStatus):ScfAssessmentStatus{return status==="not_started"?"not_tested":"partial";}
  private statusUntilObserved(state:ScenarioProjection):ScfAssessmentStatus{return state.status==="not_started"?"not_tested":"partial";}
}
