import type { ScreenId } from "../screen-runtime/screen.js";

export type CoachInsight = {
  lookingAt: string;
  whyItMatters: string;
  whatItProves: string;
  whatItDoesNotProve: string;
  suggestedNext: string;
  ibmIMeaning?: string;
  roughAnalogy?: string;
  grcTakeaway?: string;
};

export const AUDITOR_INSIGHTS: Partial<Record<ScreenId | "DISCONNECTED", CoachInsight>> = {
  WRKUSRPRF: {
    lookingAt: "A work-with list of user profiles on the partition.",
    whyItMatters: "Privileged access reviews start with who exists and who is enabled.",
    whatItProves: "Profile inventory exists and can be inspected interactively.",
    whatItDoesNotProve: "That access is appropriate, recertified, or monitored in real time.",
    suggestedNext: "Option 5 on BACKUPADM, then DSPUSRPRF USRPRF(BACKUPADM).",
  },
  DSPUSRPRF: {
    lookingAt: "Detailed user profile — authorities, status, last sign-on, data owner.",
    whyItMatters: "Special authorities (*ALLOBJ, *SAVSYS) map directly to control risk.",
    whatItProves: "A specific profile's configuration at a point in time.",
    whatItDoesNotProve: "Complete identity governance or approval workflow compliance.",
    suggestedNext: "DSPSYSVAL SYSVAL(QSECURITY) or DSPOBJAUT on PAYROLL/PAYMST.",
    grcTakeaway:
      "Clause 5: PAYADMIN Data owner *NONE — group profile alone is not accountability. OUTPUT(*OUTFILE) writes QGPL/USERS rows queryable via qsys2.outfile_export.",
  },
  DSPSYSVAL: {
    lookingAt: "A system-wide security configuration value.",
    whyItMatters: "Baseline hardening checks often include QSECURITY level.",
    whatItProves: "The displayed value matches what the system reports.",
    whatItDoesNotProve: "Effective access governance or monitoring by itself.",
    suggestedNext: "DSPOBJAUT OBJ(PAYROLL/PAYMST) OBJTYPE(*FILE).",
  },
  DSPOBJAUT: {
    lookingAt: "Object authority — who can use a sensitive file.",
    whyItMatters: "Segregation-of-duties failures often appear as object authority.",
    whatItProves: "Public and user-specific authority on a named object.",
    whatItDoesNotProve: "Application-layer controls or database row security.",
    suggestedNext: "DSPFD FILE(PAYROLL/PAYMST) — see which fields are PII.",
    grcTakeaway: "ISO 27701 Clause 8 starts with who can touch the payroll file.",
  },
  DSPOBJD: {
    lookingAt: "Object description — type, owner, create date, public authority.",
    whyItMatters: "Inventory and ownership evidence precedes authority review on sensitive files.",
    whatItProves: "The object exists, who owns it, and baseline *PUBLIC authority.",
    whatItDoesNotProve: "Field-level privacy controls or encryption.",
    suggestedNext: "Option 8 on WRKOBJ for DSPOBJAUT, or DSPFD for record layout.",
    grcTakeaway: "SOC 2 CC6 — object inventory on the green screen, not only in a CMDB export.",
  },
  DSPFD: {
    lookingAt: "Physical file description — record format and field list for PAYMST.",
    whyItMatters: "Privacy inventories must name where SSN and pay data live on IBM i.",
    whatItProves: "The SSN column exists in the native DB2 file layout.",
    whatItDoesNotProve: "Encryption, masking, or lawful basis for processing.",
    suggestedNext: "WRKJOBSCDE — which batch jobs read PAYMST?",
    grcTakeaway: "i on GRC Clause 8 article: DB2 tables are not abstract — they are files.",
  },
  DSPFFD: {
    lookingAt: "File field description — column names, types, and lengths for PAYMST.",
    whyItMatters: "Privacy inventories must name SSN and pay fields at the native file level.",
    whatItProves: "Which columns exist in the physical file record format.",
    whatItDoesNotProve: "Masking, tokenization, or lawful basis for processing.",
    suggestedNext: "Compare field list to DSPOBJAUT users who can read the file.",
    grcTakeaway: "Tier A layout — DSPFFD is how operators prove where PII lives on IBM i.",
  },
  WRKJOBSCDE: {
    lookingAt: "Scheduled batch entries — including payroll close and IFS export.",
    whyItMatters: "PII processing often happens in QBATCH, not interactive menus.",
    whatItProves: "Named jobs (PAYROLLNGT, PAYIFSEXP) touch payroll data on a schedule.",
    whatItDoesNotProve: "Data-owner approval, encryption in transit, or export monitoring.",
    suggestedNext: "Option 5 on PAYIFSEXP, then WRKLNK OBJ('/payroll').",
    grcTakeaway: "Clause 8 operational privacy — batch is where 'it always ran that way' hides.",
  },
  DSPJOBSCDE: {
    lookingAt: "A single job schedule entry — command text and frequency.",
    whyItMatters: "Export jobs (CPYTOIMPF to IFS) are common privacy finding paths.",
    whatItProves: "The scheduled command and owner profile for this batch path.",
    whatItDoesNotProve: "That exports are encrypted, logged, or approved.",
    suggestedNext: "WRKLNK OBJ('/payroll') for the symlink target.",
  },
  WRKLNK: {
    lookingAt: "IFS object links — symlinks from /payroll to native PAYMST.",
    whyItMatters: "Integration teams use IFS paths; auditors must follow the data flow.",
    whatItProves: "paymst.sym points at PAYROLL/PAYMST on the partition.",
    whatItDoesNotProve: "External transfers, API gateways, or cloud egress controls.",
    suggestedNext: "DSPJRN JRN(QSYS/QAUDJRN) for access events, then WRKFINDING.",
    grcTakeaway: "Clause 8: object auth + batch + IFS — the full green-screen chain.",
  },
  WRKAUTL: {
    lookingAt: "Authorization lists — grouped object security on IBM i.",
    whyItMatters: "PAYROLL autl membership should align with PAYMST object authority.",
    whatItProves: "Authorization lists exist and can be inspected (option 5 → DSPAUTL).",
    whatItDoesNotProve: "Privacy risk treatment or measurable objectives (Clause 6).",
    suggestedNext: "Option 5 beside PAYROLL, compare to DSPOBJAUT on PAYMST.",
  },
  WRKOBJOWN: {
    lookingAt: "Objects owned by a user profile — ownership accountability review.",
    whyItMatters: "Clause 10: ownership must align with business accountability, not stale IDs.",
    whatItProves: "PAYADMIN owns PAYMST; QPGMR still owns source files while disabled.",
    whatItDoesNotProve: "Data-owner assignment in your privacy register.",
    suggestedNext: "Option 5 on PAYMST, then DSPUSRPRF USRPRF(PAYADMIN) for owner field.",
    grcTakeaway: "COSO/SOC 2: WRKOBJOWN exposes ownership drift before corrective action.",
  },
  EDTAUTL: {
    lookingAt: "Editable authorization list — users and list authority on PAYROLL.",
    whyItMatters: "Clause 10 remediation often moves access into AUTL structure.",
    whatItProves: "Who is on PAYROLL autl and whether *PUBLIC is excluded.",
    whatItDoesNotProve: "Approval ticket or before/after export for auditors.",
    suggestedNext: "Option 4 to remove stale users, then DSPAUTL to verify result.",
    grcTakeaway: "Pair EDTAUTL changes with DSPAUTL before/after evidence.",
  },
  DSPAUTL: {
    lookingAt: "Members of an authorization list — users and their list authority.",
    whyItMatters: "Privacy planning (Clause 6) ties authorities to measurable objectives.",
    whatItProves: "Who is on the PAYROLL list and whether *PUBLIC is excluded.",
    whatItDoesNotProve: "Complete SoD or recertification of list membership.",
    suggestedNext: "DSPJRN or WRKFINDING to close the CLAIMS-003 narrative.",
  },
  ANZPRFACT: {
    lookingAt: "Inactive profile analysis — candidates exceeding the INACT threshold.",
    whyItMatters: "Offboarding hygiene requires scheduled sweeps, not one-time reviews.",
    whatItProves: "Profiles idle beyond policy (OLDVENDOR, BACKUPADM) are visible.",
    whatItDoesNotProve: "TPRM tickets or vendor contract termination.",
    suggestedNext: "CHGACTPRFL for exemptions, CHGUSRPRF to disable stale vendors.",
    grcTakeaway: "From the Offboarding article — ANZPRFACT is the operator receipt.",
  },
  CHGACTPRFL: {
    lookingAt: "Activity profile list — exempt profiles from inactive disable.",
    whyItMatters: "Distinguishes approved dormant privileged IDs from vendor ghosts.",
    whatItProves: "BACKUPADM (or similar) documented on the exempt list.",
    whatItDoesNotProve: "Approval workflow or periodic revalidation of exemptions.",
    suggestedNext: "CHGUSRPRF USRPRF(OLDVENDOR) STATUS(*DISABLED).",
  },
  DSPJRN: {
    lookingAt: "Security audit journal entries.",
    whyItMatters: "Logging and monitoring controls need reviewable events.",
    whatItProves: "Security-relevant events were captured in the synthetic journal.",
    whatItDoesNotProve: "Timely review, alerting, or retention policy compliance.",
    suggestedNext: "WRKFINDING, then SUBMITMSN.",
    grcTakeaway: "Blue Team article: correlate CP, AF, and PW into one timeline.",
  },
  DSPSECAUD: {
    lookingAt: "Security audit configuration plus authority-failure journal entries.",
    whyItMatters: "Clause 6 needs both monitoring baseline (QAUDCTL) and signal (AF).",
    whatItProves: "Auditing control value and AF events are visible on one screen.",
    whatItDoesNotProve: "Privacy objectives are measured or reviewed on schedule.",
    suggestedNext: "DSPAUDJRNE ENTTYP(AF PW) or DSPJRN for full timeline.",
    grcTakeaway: "i on GRC Clause 6 — authorities + QAUDJRN monitoring.",
  },
  DSPAUDJRNE: {
    lookingAt: "Filtered audit journal by entry type (ENTTYP).",
    whyItMatters: "Blue Team triage starts with AF/PW before exporting to a SIEM.",
    whatItProves: "Named entry types occurred and are reviewable at the source.",
    whatItDoesNotProve: "Automated alerting or incident tickets were opened.",
    suggestedNext: "CPYAUDJRNE for export artifact, then WRKACTJOB for live jobs.",
    grcTakeaway: "Blue Team article path — filter before you forward.",
  },
  CPYAUDJRNE: {
    lookingAt: "Journal export to outfile — repeatable monitoring extract.",
    whyItMatters: "COSO monitoring activities need scheduled QAUDJRN review, not audit-week dumps.",
    whatItProves: "Filtered entries are written to QGPL/AUDJRN and queryable via qsys2.outfile_export.",
    whatItDoesNotProve: "SIEM ingestion or management review of the extract.",
    suggestedNext: "RUNSQL QSYS2.DISPLAY_JOURNAL for SQL-side evidence engineering.",
    grcTakeaway: "COSO article — CPYAUDJRNE pairs with DSPAUDJRNE for monitoring rhythm.",
  },
  WRKACTJOB: {
    lookingAt: "Active jobs across subsystems — interactive and batch.",
    whyItMatters: "Detect starts with what is running now, not last month's report.",
    whatItProves: "OLDVENDOR VENDORJOB on QBATCH is visible in the live job table.",
    whatItDoesNotProve: "Anyone investigated or ended the job.",
    suggestedNext: "DSPAUDJRNE ENTTYP(AF PW) for correlated journal signal.",
    grcTakeaway: "Blue Team: dormant vendor ID still doing batch work.",
  },
  DSPAUT: {
    lookingAt: "User profile authorities — special authorities and limits.",
    whyItMatters: "Clause 6 privacy risk planning includes who can exceed normal authority.",
    whatItProves: "BACKUPADM (or named user) special authorities at a point in time.",
    whatItDoesNotProve: "Risk treatment or approval for those authorities.",
    suggestedNext: "WRKAUTL PAYROLL list — compare group vs individual authority.",
  },
  DSPJOBLOG: {
    lookingAt: "Messages for the active job — commands and diagnostics.",
    whyItMatters: "Respond workflows need the command that caused the journal event.",
    whatItProves: "Session-level messages including authority failures.",
    whatItDoesNotProve: "Escalation to SOC or ticket closure.",
    suggestedNext: "DSPJRN to align job log time with journal entries.",
    grcTakeaway: "Blue Team: >> prefix marks the command still running — stock DSPJOBLOG convention.",
  },
  DSPJOBATTR: {
    lookingAt: "Job status attributes — subsystem, ACTIVE/HOLD, BATCH/INT, current program.",
    whyItMatters: "Detect/respond needs job context before ending or holding a suspicious task.",
    whatItProves: "Named job runs in expected subsystem with identifiable program stack.",
    whatItDoesNotProve: "Malware analysis or adopted-authority chain depth.",
    suggestedNext: "Option 10 on DSPJOB menu → DSPJOBLOG for command trace.",
    grcTakeaway: "Reached from WRKACTJOB option 5 — same path IBM operators use under pressure.",
  },
  WRKPTFGRP: {
    lookingAt: "Installed PTF groups — cumulative, HIPER, database, and product groups.",
    whyItMatters: "ITGC change management expects current SF99740/SF99739 levels vs PSP, not 'we patch sometimes.'",
    whatItProves: "Group IDs, levels, and Installed status visible on the green screen.",
    whatItDoesNotProve: "Change tickets, test results, or MFPTF remediation.",
    suggestedNext: "Option 5 on SF99740 → DSPPTFGRP; DSPPTF on an individual fix for cover letter.",
    grcTakeaway: "SOC2 CC8.1 — patch currency is partition evidence, not a spreadsheet assertion.",
  },
  DSPPTF: {
    lookingAt: "Individual PTF detail — status, save file, action pending, cover letter.",
    whyItMatters: "Auditors tie fixes to IPL windows and special instructions in the cover letter.",
    whatItProves: "Permanent vs temporary status and whether IPL is pending.",
    whatItDoesNotProve: "That the PTF was tested in a non-prod LPAR first.",
    suggestedNext: "WRKPTFGRP to confirm group level after cumulative apply.",
    grcTakeaway: "QMGTOOLS COLESADTA prints DSPPTF for IBM Support — same data auditors want for ITGC.",
  },
  WRKSBMJOB: {
    lookingAt: "Submitted batch jobs — waiting, running, or held on QBATCH.",
    whyItMatters: "Availability tail risk hides in batch queues, not interactive uptime dashboards.",
    whatItProves: "NIGHTRUN failure and BACKUPJOB held are visible before leadership reviews ASP charts.",
    whatItDoesNotProve: "Automated alerting or runbook execution.",
    suggestedNext: "Option 5 on NIGHTRUN → DSPJOB, then DSPMSG MSGQ(QSYSOPR).",
    grcTakeaway: "Black Swan essay — batch is where green-screen stability myths break.",
  },
  WRKSYSSTS: {
    lookingAt: "System status — CPU, ASP, and job counts (active, waiting, held).",
    whyItMatters: "Uptime narratives often ignore held batch and waiting jobs.",
    whatItProves: "Held/waiting job counts can contradict a 'partition is fine' story.",
    whatItDoesNotProve: "DR readiness or RTO/RPO compliance.",
    suggestedNext: "WRKSBMJOB to name the held/failed jobs behind the metrics.",
    grcTakeaway: "ISO 27001 A.17 — availability planning needs batch visibility, not CPU alone.",
  },
  DSPMSG: {
    lookingAt: "Operator message queue — QSYSOPR system messages.",
    whyItMatters: "Batch failures often land here before any SIEM rule fires.",
    whatItProves: "NIGHTRUN abnormal end and BACKUPJOB held messages exist at the source.",
    whatItDoesNotProve: "Someone read or acted on the queue.",
    suggestedNext: "DSPJOBLOG on the failed job, then WRKFINDING for tail-risk gap.",
  },
  EDTOBJAUT: {
    lookingAt: "Object authority editor — grant/revoke paths on a named object.",
    whyItMatters: "Red team escape attempts use EDTOBJAUT when GRTOBJAUT is blocked.",
    whatItProves: "Whether LMTCPB(*YES) profiles reach the edit panel on PAYMST.",
    whatItDoesNotProve: "Application-layer authorization or adopted-program paths.",
    suggestedNext: "If denied with CPF9902, check DSPJRN ENTTYP(AF) for the attempt.",
    grcTakeaway: "Red Team article — denial is a successful boundary finding, not a lab failure.",
  },
  GRTOBJAUT: {
    lookingAt: "Grant object authority from the command line.",
    whyItMatters: "Classic privilege-escalation attempt on sensitive payroll files.",
    whatItProves: "APCLERK cannot self-grant *ALL on PAYROLL/PAYMST in this partition.",
    whatItDoesNotProve: "No other escalation path (adopted authority, IFS, SQL).",
    suggestedNext: "DSPOBJAUT OBJ(PAYROLL/PAYMST) before and after any QSECOFR remediation.",
    grcTakeaway: "Document CPF9902 plus AF journal — boundary held.",
  },
  DSPNETA: {
    lookingAt: "Network attributes — host servers and TCP/IP listeners.",
    whyItMatters: "Red team recon maps Telnet, ODBC, and NetServer exposure.",
    whatItProves: "Perimeter services visible without admin mutation rights.",
    whatItDoesNotProve: "Firewall rules or exit-point compensating controls.",
    suggestedNext: "NETSTAT OPTION(*CNN) for live connections, then WRKFINDING.",
    grcTakeaway: "Red Team article — network surface is part of the attack model.",
  },
  CFGTCP: {
    lookingAt: "Configure TCP/IP menu — interfaces, routes, domain, applications.",
    whyItMatters: "Network hardening starts at the stock administration path auditors recognize.",
    whatItProves: "Operator can reach interface and attribute panels from one menu.",
    whatItDoesNotProve: "External firewall or IDS coverage.",
    suggestedNext: "Option 3 CHGNETA or NETSTAT for connection audit.",
    grcTakeaway: "CLAIMS-007: perimeter review uses the same CFGTCP path as production LPARs.",
  },
  CHGNETA: {
    lookingAt: "Change network attributes — domain, host name, default router.",
    whyItMatters: "Misconfigured routers or host names break segmentation narratives.",
    whatItProves: "Network baseline values are visible and mutable on the partition.",
    whatItDoesNotProve: "Change was approved through your network change process.",
    suggestedNext: "DSPNETA before/after for hardening evidence.",
    grcTakeaway: "Red team boundary — document router and domain before attesting exposure.",
  },
  CRTUSRPRF: {
    lookingAt: "Create user profile prompt — lifecycle provisioning on IBM i.",
    whyItMatters: "Offboarding packs need symmetric create/delete evidence for ITGC.",
    whatItProves: "A new profile can be created with standard USRCLS and STATUS defaults.",
    whatItDoesNotProve: "Approval workflow or joiner ticket compliance.",
    suggestedNext: "DLTUSRPRF USRPRF(TRAINER01) to complete the lifecycle drill.",
    grcTakeaway: "SOC 2 CC6 — profile creation is a journal UA event in the lab.",
  },
  DLTUSRPRF: {
    lookingAt: "Delete user profile prompt — offboarding remediation path.",
    whyItMatters: "Stale vendor IDs must be removable, not only disabled.",
    whatItProves: "Lab-created profiles can be deleted with audit trail.",
    whatItDoesNotProve: "All orphaned profiles were identified enterprise-wide.",
    suggestedNext: "DSPJRN ENTTYP(UA) for create/delete correlation.",
    grcTakeaway: "Offboarding article — pair DLTUSRPRF with ANZPRFACT candidates.",
  },
  NETSTAT: {
    lookingAt: "TCP/IP network status menu — interfaces, routes, connections.",
    whyItMatters: "Connection audits prove who is connected and which listeners are open.",
    whatItProves: "Option paths to interface, route, and connection subfiles.",
    whatItDoesNotProve: "Encrypted transport or VPN compensating controls.",
    suggestedNext: "Option 3 for ESTABLISHED sessions on port 5250.",
    grcTakeaway: "Red team recon — NETSTAT *CNN before privilege escalation attempts.",
  },
  DSPCMDCOV: {
    lookingAt: "Command catalog coverage — implemented vs promptable by category.",
    whyItMatters: "Stakeholder demos need honest depth metrics, not hand-waved parity.",
    whatItProves: "Which command families are display vs stateful in this lab build.",
    whatItDoesNotProve: "Parity with a live 7.4 LPAR command set.",
    suggestedNext: "Pick a thin category and drill WRK* + golden layout for one screen.",
    grcTakeaway: "Hiring-manager lane — coverage grid backs fidelity roadmap claims.",
  },
  FINDING: {
    lookingAt: "Audit finding editor — observation, control mapping, decision impact.",
    whyItMatters: "Audit-ready findings describe what; decision-ready findings say who must act.",
    whatItProves: "You can tie green-screen evidence to a governance narrative.",
    whatItDoesNotProve: "Management accepted or remediated the risk.",
    suggestedNext: "Fill Decision impact before SUBMITMSN — leadership needs the so-what.",
    grcTakeaway: "Audit-Ready vs Decision-Ready article — severity plus impact field.",
  },
  DSPEVDDIFF: {
    lookingAt: "Before/after state changes from privileged activity.",
    whyItMatters: "Change detection is core to ITGC and access governance.",
    whatItProves: "A mutation occurred and left a reviewable diff.",
    whatItDoesNotProve: "The change was approved through your organization's process.",
    suggestedNext: "GENRPT TYPE(*PRIV) if in QSECOFR lane.",
  },
};
