import type { ScreenDefinition } from "../screen.js";
import { ibmScreenHeader, outputField } from "./screenHelpers.js";

export function createDisplaySpooledFileScreen(
  systemName: string,
  fileName: string,
  userName: string,
  spoolNumber: string,
  status: string,
): ScreenDefinition {
  const lines = [
    `Spooled file ${fileName} (${spoolNumber})`,
    `User  . . . . . . . . . . . . : ${userName}`,
    `Status  . . . . . . . . . . . : ${status}`,
    "",
    "Report output (simulated):",
    "  CLAIMS400 security audit report",
    "  Generated by batch job for evidence review.",
    "  Review privileged profiles and PAYMST authority.",
  ];
  const fields = [ibmScreenHeader("DSPSPLF", "Display Spooled File", systemName)];
  lines.forEach((line, index) => {
    fields.push(outputField(`LINE${index}`, 3 + index, 6, line.padEnd(74).slice(0, 74)));
  });
  fields.push(outputField("FKEYS", 24, 1, "F3=Exit   F12=Cancel".padEnd(80)));
  return {
    id: "DSPSPLF",
    title: "Display Spooled File",
    rows: 24,
    cols: 80,
    fields,
    functionKeys: [
      { key: "F3", label: "Exit", action: "EXIT_MENU" },
      { key: "F12", label: "Cancel", action: "CANCEL" },
    ],
  };
}

export function createWorkMessageQueueScreen(
  systemName: string,
  queueName: string,
  messageCount: number,
): ScreenDefinition {
  return {
    id: "WRKMSGQ",
    title: "Work with Message Queue",
    rows: 24,
    cols: 80,
    fields: [
      ibmScreenHeader("WRKMSGQ", "Work with Message Queue", systemName),
      outputField("QUEUE", 3, 6, `Queue . . . . . . . . . . . . : ${queueName}`),
      outputField("COUNT", 4, 6, `Messages  . . . . . . . . . . : ${messageCount}`),
      outputField("HINT", 6, 6, "Use DSPMSG MSGQ(QSYSOPR) to display messages."),
      outputField("FKEYS", 24, 1, "F3=Exit   F12=Cancel".padEnd(80)),
    ],
    functionKeys: [
      { key: "F3", label: "Exit", action: "EXIT_MENU" },
      { key: "F12", label: "Cancel", action: "CANCEL" },
    ],
  };
}

export function createWorkLicenseInfoScreen(systemName: string): ScreenDefinition {
  return {
    id: "WRKLICINF",
    title: "Work with License Information",
    rows: 24,
    cols: 80,
    fields: [
      ibmScreenHeader("WRKLICINF", "Work with License Information", systemName),
      outputField("L1", 4, 6, "Product ID  . . . . . . . . . : 5770-SS1"),
      outputField("L2", 5, 6, "License term  . . . . . . . . : *PERPETUAL"),
      outputField("L3", 6, 6, "Feature  . . . . . . . . . . . : *BASE"),
      outputField("L4", 7, 6, "Expiration  . . . . . . . . . : *NONE"),
      outputField("FKEYS", 24, 1, "F3=Exit   F12=Cancel".padEnd(80)),
    ],
    functionKeys: [
      { key: "F3", label: "Exit", action: "EXIT_MENU" },
      { key: "F12", label: "Cancel", action: "CANCEL" },
    ],
  };
}
